jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate .env.local file for SvelteKit/Vite build
        run: |
          cat <<EOF > .env.local
          PRIVATE_ENV_VAR=${{ secrets.PRIVATE_ENV_VAR }}
          EOF

      - name: Docker login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push container image
        env:
          APP_BUILD_IMAGE: ${{ env.APP_IMAGE }}:build-${{ github.run_number }}
          APP_LATEST_IMAGE: ${{ env.APP_IMAGE }}:latest
        run: |
          docker build -t ${{ env.APP_BUILD_IMAGE }} -t ${{ env.APP_LATEST_IMAGE }} .
          docker push --all-tags ${{ env.APP_IMAGE }}

      # With GitHub-hosted runners, the .env.local file is ephemeral and removed after the job ends.
      # Run `rm .env.local` command ourselves for paranoia / security hygiene
      - name: Clean up sensitive .env.local
        run: rm .env.local

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Push block to Contensis
        uses: contensis/block-push@v1
        with:
          alias: automotron
          project-id: svelteTest
          block-id: sveltekit-app
          image-uri: ${{ env.APP_IMAGE }}:build-${{ github.run_number }}
          release: true
          client-id: ${{ secrets.1989f720-d4a3-46f7-b5e3-5553336af197 }}
          shared-secret: ${{ secrets.42d9a16bc71c4515a91905d0f441d4ac-7b9565defa5f46bfba90357138048f9e-59690b67419f4b9f9e78c8b36cf1d70d }}
