name: Build and Deploy Contensis Block

on:
  workflow_dispatch:

env:
  APP_IMAGE: ghcr.io/graemeprescott/react-leif-example/${{ github.ref_name }}/app

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate .env.local file
        run: |
          cat <<EOF > .env.local
          PRIVATE_ENV_VAR=${{ secrets.PRIVATE_ENV_VAR }}
          EOF

      - name: Docker login
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push container image
        env:
          APP_BUILD_IMAGE: ${{ env.APP_IMAGE }}:build-${{ github.run_number }}
          APP_LATEST_IMAGE: ${{ env.APP_IMAGE }}:latest
        run: |
          docker build -t $APP_BUILD_IMAGE -t $APP_LATEST_IMAGE .
          docker push $APP_BUILD_IMAGE
          docker push $APP_LATEST_IMAGE

      - name: Clean up sensitive .env.local
        run: rm .env.local

  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Push block to Contensis
        uses: contensis/block-push@v1
        with:
          alias: bolton
          project-id: concept
          block-id: block-concept-concept-website
          image-uri: ${{ env.APP_IMAGE }}:build-${{ github.run_number }}
          release: true
          client-id: ${{ secrets.CONTENSIS_CLIENT_ID }}
          shared-secret: ${{ secrets.CONTENSIS_SHARED_SECRET }}
